simulation:
  dt: 0.05
  v_ref: 3.0

robot_spec:
  radius: 0.3
  a_max: 5.0
  steer_max: 0.5
  L: 1.0

waypoints:
  - {x: 1.0, y: 7.5, theta: 0.0}
  - {x: 30.0, y: 7.5, theta: 0.0}

obstacles:
  - {ox: 8.0, oy: 9.0, r: 0.5, vx: -0.5, vy: 0.5}
  - {ox: 10.0, oy: 4.0, r: 0.5, vx: -0.5, vy: -0.5}
  - {ox: 12.0, oy: 5.0, r: 0.5, vx: -0.5, vy: 0.5}
  - {ox: 14.0, oy: 9.0, r: 0.5, vx: -0.5, vy: -0.5}
  - {ox: 16.0, oy: 6.0, r: 0.5, vx: -0.5, vy: 0.5}
  - {ox: 18.0, oy: 14.0, r: 0.5, vx: -0.5, vy: -0.5}
  - {ox: 20.0, oy: 4.0, r: 0.5, vx: -0.5, vy: 0.5}
  - {ox: 22.0, oy: 12.0, r: 0.5, vx: -0.5, vy: -0.5}

dpcbf_params:
  k_lambda: 0.08
  k_mu: 0.48
  margin: 1.05
  eps: 1.0e-6

qp_weights:
  w_steer: 12.0
  w_a: 5.0
  rho: 20.0

discrete_cbf_config:
  gamma: 0.22
  du: 1.0e-3
  s_max: 10.0